let Readable = require("stream").Readable;

const { webFrame } = require("electron");
/**
 * Function to populate parameters area of a detector collapsible.
 *
 * @param {*} e event.
 * @param {*} detectorName String containing lowercaseDetector selected.
 */
function getParameters(e, detectorName) {
  let parametersHtml = "";

  for (let parameter in e.data[2]) {
    //create boolean checkboxes
    let parameterType = typeof e.data[2][parameter];
    if (parameterType === "boolean") {
      //Bool -> checkbox
      parametersHtml += String.raw`
          <div>
            <p>
              <label for="${parameter}">
                <input
                  type="checkbox"
                  name="${parameter}"
                  id="${parameter}"
                />
                <span>${parameter}</span>
              </label>
            </p>
          </div>`;
    } else if (parameterType === "number") {
      //Number -> textInput
      parametersHtml += String.raw`
        <div class="input-field">
          <input value="${
            e.data[2][parameter]
          }" id="${parameter}" type="text" />
          <label for="${parameter}">${parameter}</label>
        </div>`;
    }
  }

  //Replaces html
  $("#function-selector-div>ul>li.active form").html(parametersHtml);
  M.updateTextFields();

  for (let parameter in e.data[2]) {
    let parameterType = typeof e.data[2][parameter];
    if (parameterType === "boolean") {
      // atualize boolean checkboxes values
      $("#" + parameter).prop("checked", e.data[2][parameter]);

      //Bind checkboxes changes to cpp code
      $("#" + parameter).on("change", checkBoxEvent => {
        imgCreationWorker.postMessage([
          detectorName,
          "setParameters",
          parameter,
          checkBoxEvent.currentTarget.checked
        ]);
      });
    }

    //Bind enter pressed on a number text input to parameter change on cpp code
    if (parameterType === "number") {
      $("#" + parameter).on("keyup", keyupEvent => {
        if (keyupEvent.key === "Enter") {
          imgCreationWorker.postMessage([
            detectorName,
            "setParameters",
            parameter,
            keyupEvent.target.value
          ]);
        }
      });
    }
  }
}

/**
 * Function to populate debug image index radio buttons roll.
 *
 * @param {*} e Event.
 * @param {*} detectorName String containing lowercaseDetector.
 */
function getDebugImageSize(e, detectorName) {
  //html for radio buttons
  let radioHtml = "";

  if (e.data[2] == 0) {
    //if debugImages is empty
    radioHtml = String.raw`
      <label>
        <input name="${detectorName}DebugImageIndex" type="radio" />
        <span>0</span>
      </label>`;
  } else {
    for (let index = 0; index < e.data[2]; index++) {
      radioHtml += String.raw`
            <label>
              <input name="${detectorName}DebugImageIndex" type="radio" />
              <span>${index}</span>
            </label> `;
    }
  }

  //Atualize selector
  $("#function-selector-div>ul>li.active .debug-image-index-div").html(
    radioHtml
  );
}

/**
 * Function to Atualize parameter values.
 *
 * @param {*} e Event.
 */
function setParameters(e) {
  for (parameter in e.data[2]) {
    //atualize values
    let parameterType = typeof e.data[2][parameter];

    if (parameterType === "number") {
      $("#" + parameter).val(e.data[2][parameter]);
    } else if (parameterType === "boolean") {
      $("#" + parameter).prop("checked", e.data[2][parameter]);
    }
  }
}

let imgCreationWorker = new Worker("./js/imgCreationWorker.js");

//Function called whenever the worker has sent a message
imgCreationWorker.onmessage = function(e) {
  if (
    e.data == "capture is boolean" ||
    e.data == "capture closed" ||
    e.data == "Img is boolean"
  ) {
    // couldn't get image from worker, clear canvas and return false
    document
      .getElementById("video-canvas")
      .getContext("2d")
      .clearRect(0, 0, 640, 480);
    $("#capture-param").prop("disabled", false);
    $("#capture-param-btn").toggleClass("red");
    $("#capture-param-btn").text("start");
    return false;
  }

  //! Start of code used and generated by an external program, be careful when changing it
  //$start app.js:receiveMessage$

  //$start app.js:receiveMessage:yellowDetector$
  else if (e.data[0] === "yellowDetector") {
    if (e.data[1] === "getDebugImageSize") {
      getDebugImageSize(e, "yellowDetector");
      return;
    } else if (e.data[1] === "getParameters") {
      getParameters(e, "yellowDetector");
    } else if (e.data[1] === "setParameters") {
      setParameters(e);
    }
    return;
  }
  //$end app.js:receiveMessage:yellowDetector$

  //$start app.js:receiveMessage:lineDetector$
  else if (e.data[0] === "lineDetector") {
    if (e.data[1] === "getDebugImageSize") {
      getDebugImageSize(e, "lineDetector");
      return;
    } else if (e.data[1] === "getParameters") {
      getParameters(e, "lineDetector");
    } else if (e.data[1] === "setParameters") {
      setParameters(e);
    }
    return;
  }
  //$end app.js:receiveMessage:lineDetector$

  //$start app.js:receiveMessage:fieldDetector2$
  else if (e.data[0] === "fieldDetector2") {
    if (e.data[1] === "getDebugImageSize") {
      getDebugImageSize(e, "fieldDetector2");
      return;
    } else if (e.data[1] === "getParameters") {
      getParameters(e, "fieldDetector2");
    } else if (e.data[1] === "setParameters") {
      setParameters(e);
    }
    return;
  }
  //$end app.js:receiveMessage:fieldDetector2$

  //$end app.js:receiveMessage$

  //! End of code used and generated by an external program, be careful when changing it

  document
    .getElementById("video-canvas")
    .getContext("2d")
    .drawImage(e.data, 0, 0);
  e.data.close();
  let t2 = performance.now();
  // console.log('mudei a src da img ' + t2)

  requestAnimationFrame(timestamp => {
    //get next frame

    let className = "";

    document.getElementById("heap-usage").innerHTML = getMemory();

    imgCreationWorker.postMessage([
      "animation frame at " + timestamp,
      document.getElementById("capture-param").value,
      getSelectedIndex(),
      $("li.active>div.collapsible-header").text()
    ]);
  });
};

/**
 * Function to convert the return the result from process.memoryUsage to Megabytes.
 *
 * @param {*} x Array generated by process.memoryUsage.
 * @returns String containing memories in MB used by process.
 */
function logBytes(x) {
  return x[0] + x[1] / (1000.0 * 1000) + " MB <br>";
}

/**
 * Function to get memories used by the program.
 *
 * @returns String contaning the use of each memory type.
 */
function getMemory() {
  return Object.entries(process.memoryUsage())
    .map(logBytes)
    .toString();
}

/**
 * Function called when main video need to be started or stopped.
 *
 * @param {*} e Event.
 */
function videoTriedToBeStartedOrStopped(e) {
  let className = ""; //current selected detector class

  if ($("#capture-param-btn").text() == "stop") {
    //Stop video
    imgCreationWorker.postMessage("stop");
  } else {
    // Start video
    $("#capture-param").prop("disabled", true);
    $("#capture-param-btn").toggleClass("red");
    $("#capture-param-btn").text("stop");

    imgCreationWorker.postMessage([
      "Sent from " + e.target.id,
      document.getElementById("capture-param").value, //capture address
      getSelectedIndex(), //index selected
      $("li.active>div.collapsible-header").text() //detector name
    ]);
    className = $("#function-selector-div>ul>li.active")
      .children()
      .first()
      .text();
    if (className) {
      //there is a class selected
      //! Start of code used and generated by an external program, be careful when changing it
      //$start app.js:videoTriedToBeStartedOrStopped$

      //$start app.js:videoTriedToBeStartedOrStopped:yellowDetector$
      if (className.includes("Yellow Detector")) {
        imgCreationWorker.postMessage(["yellowDetector", "getDebugImageSize"]);
      }
      //$end app.js:videoTriedToBeStartedOrStopped:yellowDetector$

      //$start app.js:videoTriedToBeStartedOrStopped:lineDetector$
      if (className.includes("Line Detector")) {
        imgCreationWorker.postMessage(["lineDetector", "getDebugImageSize"]);
      }
      //$end app.js:videoTriedToBeStartedOrStopped:lineDetector$

      //$start app.js:videoTriedToBeStartedOrStopped:fieldDetector2$
      if (className.includes("Field Detector2")) {
        imgCreationWorker.postMessage(["fieldDetector2", "getDebugImageSize"]);
      }
      //$end app.js:videoTriedToBeStartedOrStopped:fieldDetector2$

      //$end app.js:videoTriedToBeStartedOrStopped$
      //! End of code used and generated by an external program, be careful when changing it
    }
  }
}

/**
 * Function called when a detector is selected
 *
 * @param {*} event Event.
 */
function detectorClicked(event) {
  if (
    event.currentTarget.parentElement.classList["toString"]().includes("active")
  ) {
    //If it is already selected, deactivate detector
    //Base collapsible body html
    event.currentTarget.nextElementSibling.innerHTML = String.raw`
    <div class="collapsible-body-grid">
      <div class="debug-image-index-div">
        <label>
          <input name="detector-debug-image-index-selector#" type="radio" checked />
          <span>0</span>
        </label>
      </div>
      <div class="parameters-div">
        <form></form>
      </div>
    </div>`;
  }
  let className = event.target.innerText;
  //! Start of code used and generated by an external program, be careful when changing it

  //$start app.js:detectorClicked$

  //$start app.js:detectorClicked:yellowDetector$
  if (className.includes("Yellow Detector")) {
    imgCreationWorker.postMessage([
      "detectorStarted",
      document.getElementById("capture-param").value,
      getSelectedIndex(),
      "Yellow Detector"
    ]);
    imgCreationWorker.postMessage(["yellowDetector", "getDebugImageSize"]);
    imgCreationWorker.postMessage(["yellowDetector", "getParameters"]);
  }
  //$end app.js:detectorClicked:yellowDetector$

  //$start app.js:detectorClicked:lineDetector$
  if (className.includes("Line Detector")) {
    imgCreationWorker.postMessage([
      "detectorStarted",
      document.getElementById("capture-param").value,
      getSelectedIndex(),
      "Line Detector"
    ]);
    imgCreationWorker.postMessage(["lineDetector", "getDebugImageSize"]);
    imgCreationWorker.postMessage(["lineDetector", "getParameters"]);
  }
  //$end app.js:detectorClicked:lineDetector$

  //$start app.js:detectorClicked:fieldDetector2$
  if (className.includes("Field Detector2")) {
    imgCreationWorker.postMessage([
      "detectorStarted",
      document.getElementById("capture-param").value,
      getSelectedIndex(),
      "Field Detector2"
    ]);
    imgCreationWorker.postMessage(["fieldDetector2", "getDebugImageSize"]);
    imgCreationWorker.postMessage(["fieldDetector2", "getParameters"]);
  }
  //$end app.js:detectorClicked:fieldDetector2$

  //$end app.js:detectorClicked$

  //! End of code used and generated by an external program, be careful when changing it
}

/**
 * Get selected debugImage index
 *
 * @returns String contaning a number, which is the selected index, or 0.
 */
function getSelectedIndex() {
  let indexSelected = "";
  try {
    for (let input of document
      .querySelector("li.active .debug-image-index-div")
      .getElementsByTagName("input")) {
      if (input.checked) {
        indexSelected = input.nextElementSibling.textContent;
        return indexSelected;
      }
    }
  } catch (error) {
    if (error.message == "Cannot read property 'getElementsByTagName' of null")
      return "0";
    else {
      throw error;
    }
  }
}

// Main function. Called when page is loaded
$(function() {
  $(document).ready(function() {
    // Access the DOM elements here...
    console.log("appjs");
    M.AutoInit();

    // -----------------bindings---------------------------
    //bind pressing of enter inside the capture parameter text input
    $("#capture-param").on("keyup", function(e) {
      if (e.keyCode == 13) {
        videoTriedToBeStartedOrStopped(e);
      }
    });

    //bind video start/stop button
    $("#capture-param-btn").on("click", function(e) {
      videoTriedToBeStartedOrStopped(e);
    });

    //bind detector selection
    $(".function-selection>ul>li>.collapsible-header").on("click", e => {
      detectorClicked(e);
    });

    //collapsible size once opened
    let detectorSelectionCollapsibleheight = $("#function-selector-div>ul")
      .first()
      .height();
    $("#function-selector-div>.collapsible").prop(
      "M_Collapsible"
    ).options.onOpenEnd = li => {
      li.lastElementChild.style["height"] =
        parseInt(
          document.documentElement.clientHeight -
            detectorSelectionCollapsibleheight -
            parseInt(window.getComputedStyle(li).marginTop) -
            parseInt(window.getComputedStyle(li).marginBottom)
        ).toString() + "px";
      li.lastElementChild.style["overflow-y"] = "auto";
    };
    // -------------------------------------------------------
  });
});
